# Generated by Django 4.0.5 on 2022-06-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0011_alter_userdetails_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
