# Generated by Django 4.0.5 on 2022-06-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0012_userdetails_counter_userdetails_isverified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='isVerified',
        ),
    ]
