# Generated by Django 4.0.5 on 2022-07-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0016_alter_userdetails_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='LikeCount',
            field=models.IntegerField(null=True),
        ),
    ]
